### ISSUE TITLE
Handle different encodings extracted as text from PDF, code giving unicodedecode error

### ISSUE THREAD

**Issue by SudharshanaSL** [shreyasrkarthik/AutomaticSlidesGeneration#11]
Traceback (most recent call last):
  File "../src/driver.py", line 119, in <module>
    sentences, bullet_map = bi.identify_bullet_sentences(input_file_path)
  File "../../prototype/parser/BulletIdentifier.py", line 44, in identify_bullet_sentences
    valid_sentences = self.get_sentences(file_name)#sentences with word count in range(2,30)
  File "../../prototype/parser/BulletIdentifier.py", line 32, in get_sentences
    num_words = len(word_tokenize(sentence))
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/__init__.py", line 109, in word_tokenize
    return [token for sent in sent_tokenize(text, language)
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/__init__.py", line 94, in sent_tokenize
    return tokenizer.tokenize(text)
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 1237, in tokenize
    return list(self.sentences_from_text(text, realign_boundaries))
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 1285, in sentences_from_text
    return [text[s:e] for s, e in self.span_tokenize(text, realign_boundaries)]
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 1276, in span_tokenize
    return [(sl.start, sl.stop) for sl in slices]
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 1316, in _realign_boundaries
    for sl1, sl2 in _pair_iter(slices):
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 310, in _pair_iter
    prev = next(it)
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 1291, in _slices_from_text
    if self.text_contains_sentbreak(context):
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 1337, in text_contains_sentbreak
    for t in self._annotate_tokens(self._tokenize_words(text)):
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 1472, in _annotate_second_pass
    for t1, t2 in _pair_iter(tokens):
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 310, in _pair_iter
    prev = next(it)
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 577, in _annotate_first_pass
    for aug_tok in tokens:
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 542, in _tokenize_words
    for line in plaintext.split('\n'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0x84 in position 0: ordinal not in range(128)

**Comment by SudharshanaSL** [comment]
Cannot test pdfs until this is fixed.

**Comment by pramodvm** [comment]
This is not parser problem, Shreyas can you look into this.

**Comment by pramodvm** [comment]
Can you remove word tokenize and write our own thing?

**Comment by SudharshanaSL** [comment]
@shreyasrkarthik , please investigate into this
